
# Site settings
title: Viplav
email: tsm@email.com


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCnSt7IlsAlV69jxTes7WRMg
  - title: facebook
    url: https://www.facebook.com/viplav.k.singh.1
  - title: instagram
    url: https://www.instagram.com/viplashh/
  - title: linkedin
    url: https://www.linkedin.com/in/viplav-kumar-singh-561712136/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BK3Q49aH7Qnq3cHYoqlbTXg%3D%3D

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

collections:
  albums:
    output: True


plugins:
  - jekyll-webp

webp:
  enabled: true
  quality: 50
  img_dir: ["/assets/images"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  append_ext: true

releases:
  number: 3

videos:
  - title: Ceaseless
    description: I composed and produced this song (except the lyrics and vocal melodies which were written beautifully by Mitesh) and recorded along with my Ensemble mates Aditya Ahir (on the bass),  Sarvesh Raul (on guitar) and Kanishk Diwaker (on keys) and the results came out pretty well. This is the first time, I've recorded with my home drum kit setup 😃and have tried to keep the music simple and groovy.
    image: https://img.youtube.com/vi/dvXT-AEDoyI/0.jpg
    vid: dvXT-AEDoyI
  - title: Void
    description: I'm so excited to share this short composition that I wrote, in which I've tried to incorporate "minor" harmonic ideas (which I've been exploring for the past few months) with a bit of sampling, comping and syncopated grooves.
    image: https://img.youtube.com/vi/SffOzJk2eXQ/0.jpg
    vid: SffOzJk2eXQ


